name: Build & Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.400'
      - name: Restore dependencies - be
        run: dotnet restore
      - name: Restore dependencies - fe
        working-directory: ./app
        run: npm install
      - name: Build - be
        run: dotnet build --no-restore
      - name: Build - fe
        working-directory: ./app
        run: npm run build
      - name: Test - be
        run: dotnet test
      - name: Test - fe
        working-directory: ./app
        run: npm run test